name: Deploy Fullstack App

on:
  push:
    branches: [ main ]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    environment: production
    outputs:
      backend_url: ${{ steps.get_url.outputs.url }} 
    steps:
      - uses: actions/checkout@v2

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          cd ml_service
          railway up --service "backend-api" --detach

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend
    environment: production
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Debug directory structure
        run: |
          pwd
          ls -la
          ls -la frontend/

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        working-directory: ./frontend
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} --env NEXT_PUBLIC_API_URL=${{ needs.deploy-backend.outputs.backend_url }}